# Generated by Django 5.2.17 on 2026-09-24 10:20

import apps.missions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy(apps, schema_editor):
    Mission = apps.get_model('missions', 'Mission')
    Crew = apps.get_model('missions', 'MissionCrew')
    db = schema_editor.connection.alias
    for mission in Mission.objects.using(db).all().iterator():
        mission.mission_number = f'MSN-LEGACY-{mission.pk:06d}'
        mission.save(using=db, update_fields=['mission_number'])
        for user in mission.paramedics.using(db).all():
            Crew.objects.using(db).create(mission_id=mission.pk, user_id=user.pk, crew_role='', actual=mission.status == 'COMPLETED')


def restore_legacy(apps, schema_editor):
    Mission = apps.get_model('missions', 'Mission')
    db = schema_editor.connection.alias
    for mission in Mission.objects.using(db).all().iterator():
        mission.paramedics.set(mission.crew.values_list('user_id', flat=True).distinct())


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_brd_statuses'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MissionCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_role', models.CharField(blank=True, max_length=80)),
                ('actual', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='mission',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='destination',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='mission',
            name='incident_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_number',
            field=models.CharField(editable=False, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE'), ('vehicle__isnull', False)), fields=('vehicle',), name='one_active_mission_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(('actual_end__isnull', True), ('actual_start__isnull', True), ('actual_end__gte', models.F('actual_start')), _connector='OR'), name='mission_times_ordered'),
        ),
        migrations.AddField(
            model_name='missionaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionaudit',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missioncrew',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missioncrew',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='missioncrew',
            constraint=models.UniqueConstraint(fields=('mission', 'user', 'actual'), name='unique_mission_crew_phase'),
        ),
        migrations.RunPython(preserve_legacy, restore_legacy),
        migrations.AlterField(model_name='mission', name='mission_number', field=models.CharField(default=apps.missions.models.mission_number, editable=False, max_length=40, unique=True)),
        migrations.RemoveField(model_name='mission', name='paramedics'),
    ]
