# Generated by Django 5.2.17 on 2026-09-25 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(choices=[('OC5', 'OC5'), ('OC10', 'OC10'), ('CYL', 'CYL'), ('BP', 'BP'), ('CP', 'CP'), ('NB', 'NB'), ('WC', 'WC')], max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LOAN', 'On loan'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=16)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'ON_LOAN', 'MAINTENANCE', 'RETIRED'])), name='valid_equipment_status'), models.CheckConstraint(condition=models.Q(('type__in', ['OC5', 'OC10', 'CYL', 'BP', 'CP', 'NB', 'WC'])), name='valid_equipment_type')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=120)),
                ('borrower_phone', models.CharField(max_length=32)),
                ('borrower_address', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('due_date', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('return_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance')], max_length=16)),
                ('return_notes', models.TextField(blank=True)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_checkouts', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='equipment.equipment')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_out_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('equipment',), name='one_open_loan_per_equipment'), models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('checked_out_at')), _connector='OR'), name='equipment_return_after_checkout'), models.CheckConstraint(condition=models.Q(models.Q(('return_status', ''), ('returned_at__isnull', True), ('returned_by__isnull', True)), models.Q(('return_status__in', ['AVAILABLE', 'MAINTENANCE']), ('returned_at__isnull', False), ('returned_by__isnull', False)), _connector='OR'), name='complete_equipment_return')],
            },
        ),
    ]
