# Generated by Django 5.2.17 on 2026-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('plate_number', models.CharField(max_length=40, unique=True)),
                ('type', models.CharField(default='Ambulance', max_length=80)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_MISSION', 'On Mission'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'ON_MISSION', 'MAINTENANCE'])), name='valid_vehicle_status')],
            },
        ),
    ]
