# Generated by Django 5.2.17 on 2026-09-25 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_manual_holds(apps, schema_editor):
    apps.get_model('vehicles', 'Vehicle').objects.filter(status='MAINTENANCE').update(manual_maintenance=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='manual_maintenance',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(preserve_manual_holds, migrations.RunPython.noop),
        migrations.CreateModel(
            name='VehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_MAINTENANCE', 'In Maintenance'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_vehicle_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_vehicle_issues', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleIssueAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='vehicles.vehicleissue')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleissue',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_MAINTENANCE', 'RESOLVED'])), name='valid_vehicle_issue_status'),
        ),
        migrations.AddConstraint(
            model_name='vehicleissue',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='valid_vehicle_issue_severity'),
        ),
        migrations.AddConstraint(
            model_name='vehicleissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status', 'RESOLVED')), models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), models.Q(('status', 'RESOLVED'), _negated=True)), _connector='OR'), name='vehicle_issue_resolution_metadata'),
        ),
    ]
